name: test
on: push

jobs:
  generate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        uses: rubikloud/build-number@pre4
        with:
            token: ${{secrets.github_token}}        
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"